import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col space-y-3 w-full items-center justify-center h-screen">
        <p className=" font-bold text-5xl">Next.Js Tailwind CSS Starter</p>
        <p className="font-light text-4xl ">by Creativ0x </p>
      </div>
    </div>
  );
}
